import {useCallback,useEffect,useState} from 'react'
import type {FormEvent} from 'react'
import {Activity,Bell,Bot,ChevronDown,FileText,Gauge,Globe2,HelpCircle,KeyRound,LayoutDashboard,Link2,LoaderCircle,LogOut,Menu,Moon,Plus,Radar,Search,ShieldCheck,Sparkles,Waypoints,X} from 'lucide-react'
import {ApiError,api,session,type Crawl,type Issue,type Score,type SeoProject} from './api'
import './App.css'

const nav=[['نمای کلی',LayoutDashboard],['خزش سایت',Radar],['ممیزی و مشکلات',ShieldCheck],['کلمات کلیدی',Search],['لینک‌های داخلی',Link2],['محتوا',FileText],['رقبا',Waypoints],['دستیار هوشمند',Bot],['گزارش‌ها',Activity]] as const

function Auth({onAuthenticated}:{onAuthenticated:()=>void}){
 const[register,setRegister]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[fullName,setFullName]=useState(''),[company,setCompany]=useState(''),[confirm,setConfirm]=useState(''),[terms,setTerms]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState<Record<string,string[]>>({})
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setFields({});try{if(register)await api.register({fullName,email,companyName:company,password,confirmPassword:confirm,acceptTerms:terms,preferredLanguage:'fa'});else await api.login(email,password);onAuthenticated()}catch(x){setError(x instanceof Error?x.message:'ارتباط با سرور برقرار نشد.');if(x instanceof ApiError)setFields(x.fields)}finally{setBusy(false)}}
 const fieldError=(name:string)=>fields[name]?.map((x,i)=><small className="field-error" key={i}>{x}</small>)
 return <div className="auth-page" dir="rtl"><div className="auth-art"><div className="auth-brand"><div className="brandmark"><Gauge size={24}/></div><b>SEO Loodoi</b></div><div><span className="eyebrow"><Sparkles size={15}/>هوشمندی سئو بر پایه شواهد واقعی</span><h1>مشکل را فقط پیدا نکن؛<br/><em>دلیل و اولویت</em> آن را بفهم.</h1><p>خزش امن، تحلیل قطعی و پیشنهادهای قابل پیگیری—بدون ساختن متریک‌های غیرواقعی.</p></div><div className="auth-trust"><span><ShieldCheck/>محافظت SSRF</span><span><KeyRound/>تفکیک کامل داده کاربران</span></div></div><div className="auth-side"><form className="auth-card" onSubmit={submit}><div className="auth-mobile-brand"><Gauge/><b>SEO Loodoi</b></div><h2>{register?'ساخت حساب واقعی':'ورود به فضای کاری'}</h2><p>{register?'اطلاعات حساب و فضای کاری خود را تکمیل کنید.':'خوش آمدید؛ برای ادامه وارد حساب خود شوید.'}</p>{register&&<div className="register-grid"><label>نام و نام خانوادگی<input autoComplete="name" value={fullName} onChange={e=>setFullName(e.target.value)} placeholder="نام کامل شما" required minLength={2} maxLength={120}/>{fieldError('fullName')}</label><label>نام شرکت <em>اختیاری</em><input autoComplete="organization" value={company} onChange={e=>setCompany(e.target.value)} placeholder="نام مجموعه" maxLength={160}/>{fieldError('companyName')}</label></div>}<label>ایمیل کاری<input type="email" dir="ltr" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@company.com" required/>{fieldError('email')}</label><label>رمز عبور<input type="password" dir="ltr" autoComplete={register?'new-password':'current-password'} minLength={10} value={password} onChange={e=>setPassword(e.target.value)} placeholder="مثلاً Secure@2026" required/>{fieldError('password')}</label>{register&&<><div className="password-hint">حداقل ۱۰ کاراکتر شامل حرف بزرگ و کوچک انگلیسی، عدد و نماد</div><label>تکرار رمز عبور<input type="password" dir="ltr" autoComplete="new-password" minLength={10} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="رمز را دوباره وارد کنید" required/>{fieldError('confirmPassword')}</label><label className="terms"><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/><span>قوانین استفاده و سیاست حریم خصوصی را می‌پذیرم.</span></label>{fieldError('acceptTerms')}</>}{error&&<div className="form-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:register?'ساخت حساب و ورود':'ورود امن'}</button><div className="switch-auth">{register?'حساب دارید؟':'هنوز حساب ندارید؟'} <button type="button" onClick={()=>{setRegister(!register);setError('');setFields({})}}>{register?'وارد شوید':'حساب بسازید'}</button></div></form></div></div>
}

function App(){const[authenticated,setAuthenticated]=useState(session.hasToken());return authenticated?<Dashboard onLogout={()=>{session.clear();setAuthenticated(false)}}/>:<Auth onAuthenticated={()=>setAuthenticated(true)}/>}

function Dashboard({onLogout}:{onLogout:()=>void}){
 const[mobile,setMobile]=useState(false),[projects,setProjects]=useState<SeoProject[]>([]),[project,setProject]=useState<SeoProject|null>(null),[crawls,setCrawls]=useState<Crawl[]>([]),[issues,setIssues]=useState<Issue[]>([]),[score,setScore]=useState<Score|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[modal,setModal]=useState(false)
 const loadProject=useCallback(async(p:SeoProject)=>{try{const[c,i,s]=await Promise.all([api.crawls(p.id),api.issues(p.id),api.score(p.id)]);setCrawls(c);setIssues(i);setScore(s)}catch(x){setError(x instanceof Error?x.message:'خطا در دریافت داده‌ها')}},[])
 useEffect(()=>{api.projects().then(p=>{setProjects(p);if(p[0]){setProject(p[0]);loadProject(p[0])}}).catch(x=>{if(!session.hasToken())onLogout();else setError(x instanceof Error?x.message:'خطا')}).finally(()=>setLoading(false))},[loadProject,onLogout])
 useEffect(()=>{if(!project||!crawls.some(c=>['Queued','Running'].includes(c.status)))return;const id=setInterval(()=>loadProject(project),3000);return()=>clearInterval(id)},[project,crawls,loadProject])
 const latest=crawls[0],critical=issues.filter(x=>x.severity==='Critical'||x.severity==='High').length
 async function start(){if(!project)return;try{await api.startCrawl(project.id);await loadProject(project)}catch(x){setError(x instanceof Error?x.message:'شروع خزش ناموفق بود')}}
 async function action(a:'pause'|'resume'|'cancel'){if(!project||!latest)return;await api.crawlAction(project.id,latest.id,a);await loadProject(project)}
 function choose(id:string){const p=projects.find(x=>x.id===id);if(p){setProject(p);setCrawls([]);setIssues([]);setScore(null);loadProject(p)}}
 return <div className="app" dir="rtl">{mobile&&<div className="scrim" onClick={()=>setMobile(false)}/>}<aside className={mobile?'sidebar open':'sidebar'}><div className="brand"><div className="brandmark"><Gauge size={23}/></div><div><b>SEO Loodoi</b><span>SEO Intelligence</span></div><button className="close" onClick={()=>setMobile(false)}><X/></button></div><div className="project-label">فضای کاری</div><div className="project-select real"><span className="project-icon"><Globe2 size={17}/></span><select value={project?.id??''} onChange={e=>choose(e.target.value)}><option value="">{projects.length?'انتخاب پروژه':'هنوز سایتی اضافه نشده'}</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><ChevronDown size={16}/></div><nav>{nav.map(([label,Icon],i)=><button className={i===0?'nav-item active':'nav-item'} key={label}><Icon size={19}/><span>{label}</span>{label==='دستیار هوشمند'&&<em>AI</em>}</button>)}</nav><div className="sidebar-bottom"><div className="usage"><div><span>صفحات خزش‌شده</span><b>{latest?.pagesCrawled??0} / ۵۰۰</b></div><div className="track"><i style={{width:`${Math.min(100,(latest?.pagesCrawled??0)/5)}%`}}/></div><small>مصرف خزش پروژه فعلی</small></div><button className="nav-item"><HelpCircle size={19}/>راهنما و پشتیبانی</button><button className="nav-item" onClick={onLogout}><LogOut size={19}/>خروج</button></div></aside><main><header><button className="hamburger" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb"><span>فضای کاری</span><b>/</b><strong>نمای کلی</strong></div><div className="header-actions"><button className="lang">FA</button><button className="icon-btn"><Moon size={19}/></button><button className="icon-btn dot"><Bell size={19}/></button><div className="avatar">SL</div></div></header><div className="content">{error&&<div className="global-error">{error}<button onClick={()=>setError('')}><X/></button></div>}{loading?<div className="page-loading"><LoaderCircle className="spin"/>در حال دریافت فضای کاری…</div>:!project?<Empty onAdd={()=>setModal(true)}/>:<ProjectDashboard project={project} score={score} latest={latest} issues={issues} critical={critical} onStart={start} onAction={action}/>}<footer><span>SEO Loodoi · موتور مستقل تحلیل سئو</span><span>نسخه ۰.۲.۰ · وضعیت سرویس <i/> عملیاتی</span></footer></div></main>{modal&&<ProjectModal onClose={()=>setModal(false)} onCreated={p=>{setProjects(x=>[p,...x]);setProject(p);setModal(false);loadProject(p)}}/>}</div>
}
function Empty({onAdd}:{onAdd:()=>void}){return <section className="welcome"><div className="eyebrow"><Sparkles size={15}/>تحلیل دقیق، بدون داده ساختگی</div><h1>سلام، آماده‌ای سلامت سایتت رو<br/><span>واقعی و عمیق</span> بررسی کنی؟</h1><p>با افزودن اولین وب‌سایت، Loodoi ساختار، محتوا و لینک‌های سایت را با موتور مستقل خودش تحلیل می‌کند.</p><button className="primary" onClick={onAdd}><Globe2 size={18}/> افزودن اولین وب‌سایت</button><div className="trust"><span><ShieldCheck size={16}/>خزش امن و کنترل‌شده</span><span><KeyRound size={16}/>داده‌های شما خصوصی می‌ماند</span></div></section>}
function ProjectDashboard({project,score,latest,issues,critical,onStart,onAction}:{project:SeoProject;score:Score|null;latest?:Crawl;issues:Issue[];critical:number;onStart:()=>void;onAction:(a:'pause'|'resume'|'cancel')=>void}){const active=latest&&['Queued','Running','Paused'].includes(latest.status);return <><section className="project-hero"><div><span className="site-chip"><Globe2/>{project.normalizedHost}</span><h1>{project.name}</h1><p>داده‌های این صفحه فقط از شواهد ذخیره‌شده خزش محاسبه می‌شوند.</p></div><div className="crawl-actions">{!active&&<button className="primary" onClick={onStart}><Radar/>شروع خزش</button>}{latest?.status==='Running'&&<button onClick={()=>onAction('pause')}>توقف موقت</button>}{latest?.status==='Paused'&&<button className="primary" onClick={()=>onAction('resume')}>ادامه خزش</button>}{active&&<button className="danger-link" onClick={()=>onAction('cancel')}>لغو</button>}</div></section><section className="empty-dashboard"><div className="section-head"><div><h2>نمای کلی پروژه</h2><p>{latest?`وضعیت آخرین خزش: ${latest.status}`:'هنوز خزشی اجرا نشده است.'}</p></div>{latest&&<span className={'status-pill '+latest.status.toLowerCase()}>{latest.status}</span>}</div><div className="metrics">{[['امتیاز سئو',score?.overall?.toFixed(1)??'—',score?`نسخه ${score.version}`:'نیازمند تحلیل',Gauge],['مشکلات مهم',String(critical),`${issues.length} مشکل ثبت‌شده`,ShieldCheck],['صفحات خزش‌شده',String(latest?.pagesCrawled??0),`${latest?.pagesDiscovered??0} کشف‌شده`,FileText],['خطاهای خزش',String(latest?.errors??0),latest?.heartbeatAt?'Heartbeat ثبت شده':'بدون اجرا',Activity]].map(([a,b,c,I],i)=>{const Icon=I as typeof Gauge;return <div className="metric" key={a as string}><div className={'metric-icon c'+i}><Icon/></div><span>{a as string}</span><strong>{b as string}</strong><small>{c as string}</small></div>})}</div><div className="grid"><div className="panel"><div className="panel-title"><div><h3>مشکلات اخیر</h3><p>مرتب‌شده بر اساس شدت</p></div><span>{issues.length} مورد</span></div><div className="issue-list">{issues.slice(0,6).map(x=><div className="issue-row" key={x.id}><i className={'sev '+x.severity.toLowerCase()}/><div><b>{x.ruleCode}</b><small>{x.category}</small></div><span>{x.severity}</span></div>)}{!issues.length&&<div className="mini-empty">پس از پایان خزش، مشکلات اینجا ظاهر می‌شوند.</div>}</div></div><div className="panel checklist"><div className="panel-title"><div><h3>وضعیت خزش</h3><p>پیشرفت ذخیره‌شده و قابل ادامه</p></div></div><div className="crawl-progress"><div><span>پیشرفت صفحات</span><b>{latest?.pagesCrawled??0} / {latest?.pagesDiscovered??0}</b></div><div className="big-track"><i style={{width:`${latest?.pagesDiscovered?Math.min(100,latest.pagesCrawled/latest.pagesDiscovered*100):0}%`}}/></div><p>{latest?.status==='Running'?'خزش در پس‌زمینه فعال است و خودکار بروزرسانی می‌شود.':'برای تولید شواهد جدید، خزش را شروع کنید.'}</p></div></div></div></section></>}
function ProjectModal({onClose,onCreated}:{onClose:()=>void;onCreated:(p:SeoProject)=>void}){const[name,setName]=useState(''),[url,setUrl]=useState('https://'),[busy,setBusy]=useState(false),[error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();setBusy(true);try{onCreated(await api.createProject(name,url))}catch(x){setError(x instanceof Error?x.message:'خطا')}finally{setBusy(false)}}return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><form className="modal-card" onSubmit={submit}><button type="button" className="modal-close" onClick={onClose}><X/></button><div className="modal-icon"><Plus/></div><h2>افزودن وب‌سایت</h2><p>دامنه اصلی را وارد کنید. تنظیمات پیشرفته خزش بعداً قابل تغییر است.</p><label>نام پروژه<input value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً فروشگاه اصلی" required maxLength={160}/></label><label>آدرس وب‌سایت<input dir="ltr" value={url} onChange={e=>setUrl(e.target.value)} type="url" required/></label>{error&&<div className="form-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?<LoaderCircle className="spin"/>:'ساخت پروژه'}</button></form></div>}
export default App
