using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using SeoLoodoi.Application.Analysis;
using SeoLoodoi.Application.Content;
using SeoLoodoi.Application.Crawling;
using SeoLoodoi.Application.Jobs;
using SeoLoodoi.Application.Links;
using SeoLoodoi.Application.Urls;
using SeoLoodoi.Domain.Seo;
using SeoLoodoi.Infrastructure.Persistence;

namespace SeoLoodoi.Infrastructure.Analysis;

public sealed class AnalyzeCrawlJobHandler(AppDbContext db, IEnumerable<ISeoRule> rules, IScoringEngine scoring, IContentSimilarityEngine similarity, IInternalLinkGraph linkGraph, IUrlNormalizer normalizer) : ISeoJobHandler
{
    public SeoJobType Type => SeoJobType.AnalyzeCrawl;

    public async Task HandleAsync(SeoBackgroundJob job, CancellationToken ct)
    {
        var payload = JsonSerializer.Deserialize<CrawlJobPayload>(job.PayloadJson) ?? throw new InvalidDataException("Invalid analysis payload.");
        var crawlExists = await db.Crawls.AnyAsync(x => x.Id == payload.CrawlId && x.ProjectId == payload.ProjectId && x.Status == CrawlStatus.Completed, ct);
        if (!crawlExists) throw new InvalidOperationException("Crawl is not completed.");

        // Analysis jobs are idempotent. Remove only the evidence generated by this crawl,
        // including its recommendations, before rebuilding the deterministic snapshot.
        var previousIssueIds = await db.SeoIssues.Where(x => x.CrawlId == payload.CrawlId).Select(x => x.Id).ToListAsync(ct);
        if (previousIssueIds.Count > 0)
        {
            if (db.Database.IsRelational()) await db.Recommendations.Where(x => x.IssueId != null && previousIssueIds.Contains(x.IssueId.Value)).ExecuteDeleteAsync(ct);
            else db.Recommendations.RemoveRange(await db.Recommendations.Where(x => x.IssueId != null && previousIssueIds.Contains(x.IssueId.Value)).ToListAsync(ct));
        }
        if (db.Database.IsRelational())
        {
            await db.SeoIssues.Where(x => x.CrawlId == payload.CrawlId).ExecuteDeleteAsync(ct);
            await db.SeoScores.Where(x => x.CrawlId == payload.CrawlId).ExecuteDeleteAsync(ct);
        }
        else
        {
            db.SeoIssues.RemoveRange(await db.SeoIssues.Where(x => x.CrawlId == payload.CrawlId).ToListAsync(ct));
            db.SeoScores.RemoveRange(await db.SeoScores.Where(x => x.CrawlId == payload.CrawlId).ToListAsync(ct));
        }

        var pages = await db.CrawledUrls.AsNoTracking().Where(x => x.CrawlId == payload.CrawlId)
            .GroupJoin(db.PageSnapshots.AsNoTracking(), u => u.Id, s => s.CrawledUrlId, (u, snapshots) => new { Url = u, Snapshot = snapshots.FirstOrDefault() }).ToListAsync(ct);
        var allResults = new List<SeoRuleResult>();

        foreach (var page in pages)
        {
            var headings = DeserializeHeadings(page.Snapshot?.HeadingsJson);
            var context = new PageAnalysisContext(page.Url.Url, page.Snapshot?.Title, page.Snapshot?.MetaDescription,
                headings.Where(x => x.Level == 1).Select(x => x.Text).ToArray(), page.Snapshot?.Canonical,
                page.Url.WordCount, page.Snapshot?.ImageCount ?? 0, page.Snapshot?.MissingAltCount ?? 0, page.Url.ResponseTimeMs, page.Url.IsIndexable, headings.Select(x => x.Level).ToArray(), page.Url.StatusCode, page.Url.ContentType, page.Snapshot?.XRobotsTag);
            foreach (var rule in rules)
            {
                // Head metadata rules require an HTML snapshot. Status, transport and
                // URL-security rules remain valid for non-HTML responses.
                if (page.Snapshot is null && rule.Code is not ("BROKEN_STATUS" or "REDIRECTED_PAGE" or "CONTENT_TYPE_MISSING" or "HTTPS_ISSUE")) continue;
                var result = rule.Evaluate(context); allResults.Add(result);
                if (!result.Triggered) continue;
                var evidence = JsonSerializer.Serialize(new { page.Url.Url, result.Evidence });
                var issue = new SeoIssue(payload.ProjectId, payload.CrawlId, page.Url.Id, result.Code, result.Severity, result.Category, Title(result.Code), Description(result.Code), evidence);
                db.SeoIssues.Add(issue);
                db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, evidence));
            }
        }

        var contentDocuments = pages.Where(x => !string.IsNullOrWhiteSpace(x.Snapshot?.TextContent)).Select(x => new ContentDocument(x.Url.Id, x.Snapshot!.TextContent)).ToArray();
        foreach (var cluster in similarity.Cluster(contentDocuments, .85m))
        {
            var code = cluster.Exact ? "DUPLICATE_CONTENT" : "NEAR_DUPLICATE_CONTENT";
            var result = new SeoRuleResult(code, true, IssueSeverity.Medium, IssueCategory.Content, new("pageIds", string.Join(",", cluster.DocumentIds), $"Similarity observed: {cluster.Similarity}"));
            allResults.Add(result);
            var evidence = JsonSerializer.Serialize(new { cluster.DocumentIds, cluster.Similarity, cluster.Exact });
            var issue = new SeoIssue(payload.ProjectId, payload.CrawlId, null, code, result.Severity, result.Category, Title(code), Description(code), evidence);
            db.SeoIssues.Add(issue); db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, evidence));
        }

        var normalizedToId = pages.Select(x => (Id:x.Url.Id, Url:NormalizeOrNull(x.Url.Url))).Where(x => x.Url is not null).GroupBy(x => x.Url!, StringComparer.OrdinalIgnoreCase).ToDictionary(x => x.Key, x => x.First().Id, StringComparer.OrdinalIgnoreCase);
        var seedUrls = (await db.CrawlFrontierItems.AsNoTracking().Where(x => x.CrawlId == payload.CrawlId && x.DiscoveredFromId == null).Select(x => x.NormalizedUrl).ToListAsync(ct)).ToHashSet(StringComparer.OrdinalIgnoreCase);
        var graphPages = pages.Select(x => { var normalized = NormalizeOrNull(x.Url.Url); var root = Uri.TryCreate(x.Url.Url, UriKind.Absolute, out var uri) && uri.AbsolutePath == "/"; return new GraphPage(x.Url.Id, x.Url.Url, root, normalized is not null && seedUrls.Contains(normalized)); }).ToArray();
        var graphLinks = (await db.PageLinks.AsNoTracking().Where(x => x.CrawlId == payload.CrawlId && x.IsInternal).Select(x => new { x.SourceUrlId, x.NormalizedTarget }).ToListAsync(ct))
            .Where(x => normalizedToId.ContainsKey(x.NormalizedTarget)).Select(x => new GraphLink(x.SourceUrlId, normalizedToId[x.NormalizedTarget])).ToArray();
        foreach (var metric in linkGraph.Analyze(graphPages, graphLinks).Where(x => x.IsOrphan))
        {
            var result = new SeoRuleResult("ORPHAN_PAGE", true, IssueSeverity.High, IssueCategory.InternalLinks, new("inDegree", metric.InDegree.ToString(), "> 0 internal links"));
            allResults.Add(result);
            var evidence = JsonSerializer.Serialize(result.Evidence);
            var issue = new SeoIssue(payload.ProjectId, payload.CrawlId, metric.PageId, result.Code, result.Severity, result.Category, Title(result.Code), Description(result.Code), evidence);
            db.SeoIssues.Add(issue); db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, evidence));
        }

        // An empty crawl is not a perfect site. Do not persist a score until at least
        // one page has supplied evidence that the deterministic rules can evaluate.
        if (pages.Count > 0)
        {
            var score = scoring.Calculate(allResults);
            db.SeoScores.Add(new SeoScoreSnapshot(payload.ProjectId, payload.CrawlId, score.Overall, score.Categories, score.Version));
        }
        await db.SaveChangesAsync(ct);

        string? NormalizeOrNull(string value) { try { return normalizer.Normalize(new Uri(value)).AbsoluteUri; } catch { return null; } }
    }

    private static Recommendation CreateRecommendation(Guid projectId, Guid issueId, SeoRuleResult result, string evidence)
    {
        var priority = result.Severity switch { IssueSeverity.Critical => 95, IssueSeverity.High => 82, IssueSeverity.Medium => 65, IssueSeverity.Low => 40, _ => 20 };
        var impact = result.Severity is IssueSeverity.Critical or IssueSeverity.High ? "زیاد" : result.Severity == IssueSeverity.Medium ? "متوسط" : "کم";
        var effort = result.Code.Contains("CONTENT", StringComparison.Ordinal) ? "متوسط" : "کم";
        return new Recommendation(projectId, issueId, priority, Title(result.Code), "بر اساس شواهد ذخیره‌شده این مشکل را بررسی و پس از تأیید اصلاح کنید.", evidence, impact, effort, result.Severity == IssueSeverity.Critical ? .98m : .9m);
    }

    private static IReadOnlyList<ExtractedHeading> DeserializeHeadings(string? json)
    {
        try { return JsonSerializer.Deserialize<ExtractedHeading[]>(json ?? "[]") ?? []; } catch (JsonException) { return []; }
    }
    private static string Title(string code) => code switch
    {
        "TITLE_MISSING" => "عنوان صفحه وجود ندارد",
        "TITLE_LENGTH" => "طول عنوان صفحه مناسب نیست",
        "META_DESCRIPTION_MISSING" => "توضیحات متا وجود ندارد",
        "META_DESCRIPTION_LENGTH" => "طول توضیحات متا مناسب نیست",
        "H1_MISSING" => "عنوان H1 وجود ندارد",
        "MULTIPLE_H1" => "چند عنوان H1 در صفحه وجود دارد",
        "CANONICAL_MISSING" => "Canonical صفحه وجود ندارد",
        "CANONICAL_INVALID" => "Canonical صفحه معتبر نیست",
        "CANONICAL_MISMATCH" => "Canonical با URL صفحه همخوان نیست",
        "NOINDEX" => "صفحه Noindex است",
        "HTTPS_ISSUE" => "صفحه با HTTPS ارائه نشده است",
        "LOW_WORD_COUNT" => "محتوای صفحه کم است",
        "ALT_MISSING" => "تصویر بدون متن جایگزین وجود دارد",
        "SLOW_RESPONSE" => "پاسخ صفحه کند است",
        "HEADING_STRUCTURE" => "ساختار تیترها پرش دارد",
        "DUPLICATE_CONTENT" => "محتوای تکراری شناسایی شد",
        "NEAR_DUPLICATE_CONTENT" => "محتوای بسیار مشابه شناسایی شد",
        "ORPHAN_PAGE" => "صفحه یتیم است و لینک داخلی ندارد",
        _ => code.Replace('_', ' ')
    };
    private static string Description(string code) => $"قانون قطعی {code} بر اساس شواهد ذخیره‌شده خزش فعال شد. قبل از هر تغییر، مدرک صفحه را بررسی کنید.";
}
