using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using SeoLoodoi.Application.Analysis;
using SeoLoodoi.Application.Aeo;
using SeoLoodoi.Application.Content;
using SeoLoodoi.Application.Crawling;
using SeoLoodoi.Application.Jobs;
using SeoLoodoi.Application.Links;
using SeoLoodoi.Application.Urls;
using SeoLoodoi.Domain.Seo;
using SeoLoodoi.Infrastructure.Crawling;
using SeoLoodoi.Infrastructure.Persistence;

namespace SeoLoodoi.Infrastructure.Analysis;

public sealed class AnalyzeCrawlJobHandler(AppDbContext db, IEnumerable<ISeoRule> rules, IScoringEngine scoring, IContentSimilarityEngine similarity, IInternalLinkGraph linkGraph, IUrlNormalizer normalizer, ILogger<AnalyzeCrawlJobHandler> logger) : ISeoJobHandler
{
    public SeoJobType Type => SeoJobType.AnalyzeCrawl;

    public async Task HandleAsync(SeoBackgroundJob job, CancellationToken ct)
    {
        var payload = JsonSerializer.Deserialize<CrawlJobPayload>(job.PayloadJson) ?? throw new InvalidDataException("Invalid analysis payload.");
        using var scope = logger.BeginScope(new Dictionary<string, object> { ["CrawlId"] = payload.CrawlId, ["ProjectId"] = payload.ProjectId, ["JobId"] = job.Id });
        var crawl = await db.Crawls.SingleOrDefaultAsync(x => x.Id == payload.CrawlId && x.ProjectId == payload.ProjectId, ct)
            ?? throw new InvalidOperationException("Crawl no longer exists.");
        var analysis = await db.CrawlAnalyses.SingleOrDefaultAsync(x => x.CrawlId == payload.CrawlId, ct);
        if (analysis is null)
        {
            analysis = new CrawlAnalysis(payload.CrawlId, payload.ProjectId, job.IdempotencyKey);
            db.CrawlAnalyses.Add(analysis);
        }

        if (crawl.Status is CrawlStatus.Failed or CrawlStatus.Cancelled)
        {
            // Terminal crawl without completion: record the outcome and let the
            // job succeed so the worker does not retry a hopeless analysis.
            analysis.MarkFailed($"Crawl ended as {crawl.Status} and has no completed evidence to analyze.", DateTimeOffset.UtcNow);
            await db.SaveChangesAsync(ct);
            logger.LogWarning("Analysis skipped: crawl is in terminal state {CrawlStatus}", crawl.Status);
            return;
        }
        if (crawl.Status != CrawlStatus.Completed)
        {
            // The crawl is still active; the worker backoff will retry later.
            analysis.RecordAttemptFailure($"Crawl is {crawl.Status}; analysis waits for completion.", DateTimeOffset.UtcNow);
            await db.SaveChangesAsync(ct);
            logger.LogInformation("Analysis deferred: crawl is {CrawlStatus}", crawl.Status);
            throw new InvalidOperationException("Crawl is not completed.");
        }

        analysis.MarkRunning(DateTimeOffset.UtcNow, job.IdempotencyKey);
        await db.SaveChangesAsync(ct);
        logger.LogInformation("Analysis started for completed crawl");

        try
        {
            // Analysis jobs are idempotent. Remove only the evidence generated by this crawl,
            // including its recommendations, before rebuilding the deterministic snapshot.
            // AEO advisories have their own evidence lifecycle and must survive SEO retries.
            var previousIssueIds = await db.SeoIssues.Where(x => x.ProjectId == payload.ProjectId && x.CrawlId == payload.CrawlId && !AeoIssueRules.Codes.Contains(x.RuleCode)).Select(x => x.Id).ToListAsync(ct);
            if (previousIssueIds.Count > 0)
            {
                if (db.Database.IsRelational()) await db.Recommendations.Where(x => x.IssueId != null && previousIssueIds.Contains(x.IssueId.Value)).ExecuteDeleteAsync(ct);
                else db.Recommendations.RemoveRange(await db.Recommendations.Where(x => x.IssueId != null && previousIssueIds.Contains(x.IssueId.Value)).ToListAsync(ct));
            }
            if (db.Database.IsRelational())
            {
                await db.SeoIssues.Where(x => x.ProjectId == payload.ProjectId && x.CrawlId == payload.CrawlId && !AeoIssueRules.Codes.Contains(x.RuleCode)).ExecuteDeleteAsync(ct);
                await db.SeoScores.Where(x => x.CrawlId == payload.CrawlId).ExecuteDeleteAsync(ct);
            }
            else
            {
                db.SeoIssues.RemoveRange(await db.SeoIssues.Where(x => x.ProjectId == payload.ProjectId && x.CrawlId == payload.CrawlId && !AeoIssueRules.Codes.Contains(x.RuleCode)).ToListAsync(ct));
                db.SeoScores.RemoveRange(await db.SeoScores.Where(x => x.CrawlId == payload.CrawlId).ToListAsync(ct));
            }

            var pages = await db.CrawledUrls.AsNoTracking().Where(x => x.CrawlId == payload.CrawlId)
                .GroupJoin(db.PageSnapshots.AsNoTracking(), u => u.Id, s => s.CrawledUrlId, (u, snapshots) => new { Url = u, Snapshot = snapshots.FirstOrDefault() }).ToListAsync(ct);
            if (pages.Count == 0)
            {
                analysis.MarkNoData(DateTimeOffset.UtcNow);
                await db.SaveChangesAsync(ct);
                logger.LogWarning("Analysis finished with no data: crawl has zero persisted pages");
                return;
            }
            var urlById = pages.ToDictionary(x => x.Url.Id, x => x.Url.Url);

            var allResults = new List<SeoRuleResult>();
            foreach (var page in pages)
            {
                var headings = DeserializeHeadings(page.Snapshot?.HeadingsJson);
                var context = new PageAnalysisContext(page.Url.Url, page.Snapshot?.Title, page.Snapshot?.MetaDescription,
                    headings.Where(x => x.Level == 1).Select(x => x.Text).ToArray(), page.Snapshot?.Canonical,
                    page.Url.WordCount, page.Snapshot?.ImageCount ?? 0, page.Snapshot?.MissingAltCount ?? 0, page.Url.ResponseTimeMs, page.Url.IsIndexable, headings.Select(x => x.Level).ToArray(), page.Url.StatusCode, page.Url.ContentType, page.Snapshot?.XRobotsTag, page.Snapshot?.RobotsMeta,
                    page.Url.RedirectChainJson, page.Snapshot?.AssetsJson, page.Snapshot?.SchemaJson, page.Snapshot?.HreflangJson, page.Url.HeadersJson, page.Url.Depth, page.Snapshot?.TextContent);
                foreach (var rule in rules)
                {
                    // Head metadata rules require an HTML snapshot. Status, transport and
                    // URL-security rules declare RequiresHtmlSnapshot = false in the
                    // SeoRuleCatalog and stay valid for non-HTML responses.
                    if (page.Snapshot is null && SeoRuleCatalog.Get(rule.Code).RequiresHtmlSnapshot) continue;
                    var result = rule.Evaluate(context); allResults.Add(result);
                    if (!result.Triggered) continue;
                    var issue = CreateIssue(payload, page.Url.Id, page.Url.Url, result);
                    db.SeoIssues.Add(issue);
                    db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, issue.EvidenceJson));
                }
            }

            // Crawler v2 D3: critical raw-vs-rendered differences become issues. The stored
            // deterministic diff is the evidence; nothing here is inferred.
            var renderMismatches = await db.PageRenderEvidences.AsNoTracking()
                .Where(x => x.CrawlId == payload.CrawlId && x.Status == RenderEvidenceStatus.Rendered && x.CriticalDifferences > 0)
                .OrderBy(x => x.NormalizedUrl).Select(x => new { x.CrawledUrlId, x.NormalizedUrl, x.CriticalDifferences, x.DiffJson }).ToListAsync(ct);
            foreach (var mismatch in renderMismatches)
            {
                var changed = CriticalFields(mismatch.DiffJson);
                var result = new SeoRuleResult("JS_RENDER_MISMATCH", true, IssueSeverity.High, IssueCategory.Indexability, new("renderedVsRaw", string.Join(",", changed), "Critical SEO elements identical in raw HTML and rendered DOM"));
                allResults.Add(result);
                // Evidence consumes the stored deterministic RenderDiff (D3); the page is never recrawled here.
                var issue = CreateIssue(payload, mismatch.CrawledUrlId, mismatch.NormalizedUrl, result,
                    extra: new { mismatch.CriticalDifferences, Diff = JsonSerializer.Deserialize<JsonElement>(mismatch.DiffJson) },
                    facts: [new EvidenceFact("criticalDifferences", mismatch.CriticalDifferences.ToString(), EvidenceSource.RenderedDom, "0", mismatch.DiffJson)]);
                db.SeoIssues.Add(issue); db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, issue.EvidenceJson));
            }

            var contentDocuments = pages.Where(x => !string.IsNullOrWhiteSpace(x.Snapshot?.TextContent)).Select(x => new ContentDocument(x.Url.Id, x.Snapshot!.TextContent)).ToArray();
            foreach (var cluster in similarity.Cluster(contentDocuments, .85m))
            {
                var code = cluster.Exact ? "DUPLICATE_CONTENT" : "NEAR_DUPLICATE_CONTENT";
                var result = new SeoRuleResult(code, true, IssueSeverity.Medium, IssueCategory.Content, new("pageIds", string.Join(",", cluster.DocumentIds), $"Similarity observed: {cluster.Similarity}"));
                allResults.Add(result);
                var issue = CreateIssue(payload, null, string.Empty, result,
                    extra: new { cluster.DocumentIds, cluster.Similarity, cluster.Exact },
                    facts: [new EvidenceFact("similarity", cluster.Similarity.ToString(), EvidenceSource.RawHtml, "< 0.85 similarity between page texts", cluster.Exact ? "exact" : "near")]);
                db.SeoIssues.Add(issue); db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, issue.EvidenceJson));
            }

            var normalizedToId = pages.Select(x => (Id: x.Url.Id, Url: NormalizeOrNull(x.Url.Url))).Where(x => x.Url is not null).GroupBy(x => x.Url!, StringComparer.OrdinalIgnoreCase).ToDictionary(x => x.Key, x => x.First().Id, StringComparer.OrdinalIgnoreCase);
            var seedUrls = (await db.CrawlFrontierItems.AsNoTracking().Where(x => x.CrawlId == payload.CrawlId && x.DiscoveredFromId == null).Select(x => x.NormalizedUrl).ToListAsync(ct)).ToHashSet(StringComparer.OrdinalIgnoreCase);
            var graphPages = pages.Select(x => { var normalized = NormalizeOrNull(x.Url.Url); var root = Uri.TryCreate(x.Url.Url, UriKind.Absolute, out var uri) && uri.AbsolutePath == "/"; return new GraphPage(x.Url.Id, x.Url.Url, root, normalized is not null && seedUrls.Contains(normalized)); }).ToArray();
            var graphLinks = (await db.PageLinks.AsNoTracking().Where(x => x.CrawlId == payload.CrawlId && x.IsInternal).Select(x => new { x.SourceUrlId, x.NormalizedTarget, x.AnchorText }).ToListAsync(ct))
                .Where(x => normalizedToId.ContainsKey(x.NormalizedTarget)).Select(x => new GraphLink(x.SourceUrlId, normalizedToId[x.NormalizedTarget], x.AnchorText)).ToArray();
            var graphMetrics = linkGraph.Analyze(graphPages, graphLinks);
            foreach (var metric in graphMetrics.Where(x => x.IsOrphan))
            {
                var result = new SeoRuleResult("ORPHAN_PAGE", true, IssueSeverity.High, IssueCategory.InternalLinks, new("inDegree", metric.InDegree.ToString(), "> 0 internal links"));
                allResults.Add(result);
                var issue = CreateIssue(payload, metric.PageId, urlById.GetValueOrDefault(metric.PageId, string.Empty), result);
                db.SeoIssues.Add(issue); db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, issue.EvidenceJson));
            }
            foreach (var metric in graphMetrics.Where(x => x.IsDeadEnd))
            {
                var result = new SeoRuleResult("DEAD_END_PAGE", true, IssueSeverity.Medium, IssueCategory.InternalLinks, new("outDegree", "0", "> 0 outgoing internal links to distribute link equity"));
                allResults.Add(result);
                var issue = CreateIssue(payload, metric.PageId, urlById.GetValueOrDefault(metric.PageId, string.Empty), result);
                db.SeoIssues.Add(issue); db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, issue.EvidenceJson));
            }

            var rawInternalLinks = await db.PageLinks.AsNoTracking().Where(x => x.CrawlId == payload.CrawlId && x.IsInternal).ToListAsync(ct);
            var genericGroups = rawInternalLinks.Where(l => InternalLinkGraph.IsGenericAnchor(l.AnchorText)).GroupBy(l => l.SourceUrlId);
            foreach (var group in genericGroups)
            {
                var samples = string.Join(", ", group.Select(x => x.AnchorText).Take(3));
                var result = new SeoRuleResult("GENERIC_ANCHOR_TEXT", true, IssueSeverity.Low, IssueCategory.InternalLinks, new("genericAnchors", samples, "Descriptive keyword-relevant anchor text"));
                allResults.Add(result);
                var issue = CreateIssue(payload, group.Key, urlById.GetValueOrDefault(group.Key, string.Empty), result,
                    extra: new { count = group.Count(), samples },
                    facts: [new EvidenceFact("genericAnchorCount", group.Count().ToString(), EvidenceSource.Links, "0 generic internal anchors on one source page")]);
                db.SeoIssues.Add(issue); db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, issue.EvidenceJson));
            }

            // Snapshot is non-null and Title is non-empty/whitespace for every page that
            // survives the filter above, so the grouping key is always a real string.
            var duplicateTitleGroups = pages
                .Where(p => p.Snapshot is not null && !string.IsNullOrWhiteSpace(p.Snapshot.Title))
                .GroupBy(p => p.Snapshot!.Title!.Trim(), StringComparer.OrdinalIgnoreCase)
                .Where(g => g.Count() > 1);

            foreach (var group in duplicateTitleGroups)
            {
                var titleText = group.Key;
                foreach (var page in group)
                {
                    var otherUrls = group.Where(x => x.Url.Id != page.Url.Id).Select(x => x.Url.Url).Take(3).ToArray();
                    var result = new SeoRuleResult("DUPLICATE_TITLE_TAG", true, IssueSeverity.High, IssueCategory.OnPage,
                        new("duplicateTitle", titleText, "Unique title tag per indexed page"));
                    allResults.Add(result);
                    var issue = CreateIssue(payload, page.Url.Id, page.Url.Url, result,
                        extra: new { title = titleText, conflictingUrls = otherUrls },
                        facts: [new EvidenceFact("conflictingUrls", string.Join(",", otherUrls), EvidenceSource.RawHtml, "unique title per page")]);
                    db.SeoIssues.Add(issue);
                    db.Recommendations.Add(CreateRecommendation(payload.ProjectId, issue.Id, result, issue.EvidenceJson));
                }
            }

            var score = scoring.Calculate(allResults);
            db.SeoScores.Add(new SeoScoreSnapshot(payload.ProjectId, payload.CrawlId, score.Overall, score.Categories, score.Version, score.IsPartial));
            analysis.MarkSucceeded(DateTimeOffset.UtcNow);
            await db.SaveChangesAsync(ct);
            var issueCount = await db.SeoIssues.CountAsync(x => x.CrawlId == payload.CrawlId, ct);
            logger.LogInformation("Analysis succeeded: {Pages} pages, {Rules} rule evaluations, {Issues} issues, overall {Overall}, partial {IsPartial}",
                pages.Count, allResults.Count, issueCount, score.Overall?.ToString() ?? "null", score.IsPartial);
        }
        catch (Exception ex)
        {
            foreach (var entry in db.ChangeTracker.Entries().Where(x => x.State == EntityState.Added && (x.Entity is SeoIssue or Recommendation or SeoScoreSnapshot)).ToArray()) entry.State = EntityState.Detached;
            analysis.RecordAttemptFailure(ex.GetType().Name + ": " + ex.Message, DateTimeOffset.UtcNow);
            await db.SaveChangesAsync(ct);
            logger.LogError(ex, "Analysis attempt failed");
            throw;
        }

        string? NormalizeOrNull(string value) { try { return normalizer.Normalize(new Uri(value)).AbsoluteUri; } catch { return null; } }
    }

    /// <summary>Evidence-first issue creation (P1 Phase 2): machine-readable facts envelope plus rule metadata stamping.</summary>
    private SeoIssue CreateIssue(CrawlJobPayload payload, Guid? urlId, string url, SeoRuleResult result, object? extra = null, EvidenceFact[]? facts = null)
    {
        var metadata = SeoRuleCatalog.Get(result.Code);
        var evidence = SeoEvidence.Build(url, metadata, result.Evidence, DateTimeOffset.UtcNow, extra, facts: facts ?? []);
        return new SeoIssue(payload.ProjectId, payload.CrawlId, urlId, result.Code, result.Severity, result.Category,
            Title(result.Code), Description(result.Code), evidence, metadata.Confidence, metadata.Version);
    }

    private static Recommendation CreateRecommendation(Guid projectId, Guid issueId, SeoRuleResult result, string evidence)
    {
        var priority = result.Severity switch { IssueSeverity.Critical => 95, IssueSeverity.High => 82, IssueSeverity.Medium => 65, IssueSeverity.Low => 40, _ => 20 };
        var impact = result.Severity is IssueSeverity.Critical or IssueSeverity.High ? "زیاد" : result.Severity == IssueSeverity.Medium ? "متوسط" : "کم";
        var effort = result.Code.Contains("CONTENT", StringComparison.Ordinal) ? "متوسط" : "کم";
        return new Recommendation(projectId, issueId, priority, Title(result.Code), "بر اساس شواهد ذخیره‌شده این مشکل را بررسی و پس از تأیید اصلاح کنید.", evidence, impact, effort, result.Severity == IssueSeverity.Critical ? .98m : .9m);
    }

    private static string[] CriticalFields(string diffJson)
    {
        try
        {
            using var doc = JsonDocument.Parse(diffJson);
            return doc.RootElement.GetProperty("fields").EnumerateArray()
                .Where(f => f.GetProperty("changed").GetBoolean() && f.GetProperty("severity").GetString() == "Critical")
                .Select(f => f.GetProperty("field").GetString() ?? "?").ToArray();
        }
        catch (Exception ex) when (ex is JsonException or KeyNotFoundException or InvalidOperationException) { return []; }
    }

    private static IReadOnlyList<ExtractedHeading> DeserializeHeadings(string? json)
    {
        try { return JsonSerializer.Deserialize<ExtractedHeading[]>(json ?? "[]") ?? []; } catch (JsonException) { return []; }
    }
    private static string Title(string code) => code switch
    {
        "TITLE_MISSING" => "عنوان صفحه وجود ندارد",
        "TITLE_LENGTH" => "طول عنوان صفحه مناسب نیست",
        "META_DESCRIPTION_MISSING" => "توضیحات متا وجود ندارد",
        "META_DESCRIPTION_LENGTH" => "طول توضیحات متا مناسب نیست",
        "H1_MISSING" => "عنوان H1 وجود ندارد",
        "MULTIPLE_H1" => "چند عنوان H1 در صفحه وجود دارد",
        "CANONICAL_MISSING" => "Canonical صفحه وجود ندارد",
        "CANONICAL_INVALID" => "Canonical صفحه معتبر نیست",
        "CANONICAL_MISMATCH" => "Canonical با URL صفحه همخوان نیست",
        "NOINDEX" => "صفحه Noindex است",
        "HTTPS_ISSUE" => "صفحه با HTTPS ارائه نشده است",
        "LOW_WORD_COUNT" => "محتوای صفحه کم است",
        "ALT_MISSING" => "تصویر بدون متن جایگزین وجود دارد",
        "SLOW_RESPONSE" => "پاسخ صفحه کند است",
        "HEADING_STRUCTURE" => "ساختار تیترها پرش دارد",
        "DUPLICATE_CONTENT" => "محتوای تکراری شناسایی شد",
        "NEAR_DUPLICATE_CONTENT" => "محتوای بسیار مشابه شناسایی شد",
        "ORPHAN_PAGE" => "صفحه یتیم است و لینک داخلی ندارد",
        "REDIRECT_CHAIN_LONG" => "زنجیره تغییر مسیر بیش از حد طولانی است",
        "MIXED_CONTENT_ASSETS" => "بارگذاری منابع ناامن HTTP در صفحه HTTPS شناسایی شد",
        "EXCESSIVE_RESOURCES" => "تعداد بیش از حد اسکریپت یا فایل در صفحه وجود دارد",
        "SCHEMA_SYNTAX_INVALID" => "ساختار داده‌های اسکیما (Schema.org) نامعتبر است",
        "SCHEMA_MISSING_REQUIRED" => "ویژگی‌های الزامی داده‌های ساختاریافته وجود ندارد",
        "STRUCTURED_DATA_ABSENT" => "صفحه فاقد داده‌های ساختاریافته اسکیما است",
        "HREFLANG_NO_SELF_REFERENCE" => "تگ hreflang فاقد ارجاع به صفحه جاری است",
        "HREFLANG_INVALID_CODE" => "کد زبان در تگ hreflang معتبر نیست",
        "HSTS_MISSING" => "هدر امنیتی HSTS در پاسخ سرور وجود ندارد",
        "SECURITY_HEADERS_MISSING" => "هدرهای امنیتی دفاعی تنظیم نشده‌اند",
        "CACHE_CONTROL_MISSING" => "سیاست کش هدر Cache-Control وجود ندارد",
        "RENDER_BLOCKING_RESOURCES" => "اسکریپت‌های مسدودکننده رندر در صفحه شناسایی شد",
        "IMAGE_DIMENSIONS_MISSING" => "تصاویر فاقد ابعاد مشخص (عامل افت CLS) هستند",
        "DEAD_END_PAGE" => "صفحه بن‌بست لینک داخلی شناسایی شد (اتلاف اعتبار صفحه)",
        "GENERIC_ANCHOR_TEXT" => "انکرتکست نامفهوم یا عمومی در لینک‌های داخلی شناسایی شد",
        "DEEP_CLICK_DEPTH" => "عمق دسترسی صفحه بیش از حد زیاد است (بیش از ۳ کلیک)",
        "KEYWORD_STUFFING" => "تکرار بیش از حد کلمات کلیدی (Keyword Stuffing) شناسایی شد",
        "CONTENT_LONG_SENTENCES" => "خوانایی متن پایین است (تعداد زیاد جملات طولانی)",
        "THIN_CONTENT" => "محتوای بسیار کم و سطحی (Thin Content) شناسایی شد",
        "JS_RENDER_MISMATCH" => "عناصر حیاتی سئو در HTML خام با DOM رندرشده (جاوااسکریپت) متفاوت است",
        "DUPLICATE_TITLE_TAG" => "عنوان صفحه (Title) تکراری است و باعث تداخل رتبه (Cannibalization) می‌شود",
        _ => code.Replace('_', ' ')
    };
    private static string Description(string code) => $"قانون قطعی {code} بر اساس شواهد ذخیره‌شده خزش فعال شد. قبل از هر تغییر، مدرک صفحه را بررسی کنید.";
}
